sudo: required
services:
  - docker

before_install:
  - docker build -t younes301295/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true younes301295/react-test npm run test -- --coverage

after_success:
  - docker build -t younes301295/multi-client ./client
  - docker build -t younes301295/multi-nginx ./nginx
  - docker build -t younes301295/multi-server ./server
  - docker build -t younes301295/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push younes301295/multi-client
  - docker push younes301295/multi-nginx
  - docker push younes301295/multi-server
  - docker push younes301295/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: fibonacci-multi-docker
    env: FibonacciMultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-614153056557
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY